# Generated by Django 2.2 on 2020-11-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
