# Generated by Django 2.2 on 2020-11-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('search_term', models.TextField(blank=True, null=True)),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_author', models.CharField(blank=True, max_length=255, null=True)),
                ('description_abstract', models.TextField(blank=True, null=True)),
                ('identifier_uri', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Searchsave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('contributor_author', models.TextField(blank=True, null=True)),
                ('description_abstract', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('contributor_department', models.TextField(blank=True, null=True)),
                ('relation_haspart', models.TextField(blank=True, null=True)),
                ('contributor_committeechair', models.TextField(blank=True, null=True)),
                ('date_available', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Searchsave',
            },
        ),
    ]
