# Generated by Django 2.2 on 2020-10-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
