version: '3'

volumes:
  pgdata: {}
  esdata: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: searchx_web
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      # - elasticsearch
    env_file: .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:10.5
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d ted"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:6.6.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
